# Generated by Django 4.0.3 on 2022-05-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_technician_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='href',
        ),
    ]
