# Generated by Django 4.0.3 on 2022-05-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_rename_owner_appointment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
