# Generated by Django 4.0.3 on 2022-05-10 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_appointment_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sold_vin',
        ),
        migrations.AddField(
            model_name='appointment',
            name='automobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automobile', to='service_rest.automobilevo'),
        ),
    ]
